[package]
name = "thread_simulator"
version = "0.1.0"
authors = ["Meghana <meghanagupta3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
threadpool = "*"
spin = "*"
im = "*"