# The maximum number of cores, starting from zero, used for the server process.
max_cores = 32

# The number of child processes the server will fork.
num_tenants = 32

# The tenant_skew amount the total number of tenants.
tenant_skew = 0.9

# The number of requests that the client must generate.
num_reqs = 22000000

# The number of responses that the client must receive before printing out stats.
num_resps = 20000000

# The rate at which the client must issue requests.
req_rate = 500000

# Execute all the tasks for a tenant in one iteration.
batching = true

# Isolation mechanism amoung domains on a core. Possible values can be:
# NoIsolation, PageTableIsolation, MpkIsolation, VmfuncIsolation.
isolation = "PageTableIsolation"

# Distribution mechanism to generate requests across tenants. Possible values can be:
# Uniform, Zipf.
distribution = "Zipf"

# The Scheduling policy which is used to differentiate between short-running and long-running tasks.
# Possible values can be: RoundRobin, ShortestJF, MultiQ.
policy = "RoundRobin"
