# The IP Address for the server.
server_ip = "127.0.0.1"

# The number of child processes the server will fork.
num_process = 10

# The maximum number of cores, starting from zero, used for the server process.
max_cores = 10
