name: Rust

on: [push]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 10

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cd /home/runner/work/os_project/os_project/simulator; cargo build --verbose
    - name: Run tests
      run: cd /home/runner/work/os_project/os_project/simulator; cargo test --verbose
