name: Rust

on: [push]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Change Directory
      run: cd simulator
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
