name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: change director
      run: cd simulator
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
